---
title: "Multi-Analysis"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, cache = F, warning = T, message = T)
library(tidyverse)
library(dplyr)
library(tidyr)
library(lme4)
library(MASS)  
library(data.table)
library(Matrix)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
```


```{r}
source("DGP.R")
H = 10                                # number of sites
m_hosp = sample(10:50, H, replace=TRUE) # patients per site (vector length H)
px = 6                               # number of covariates
p_bin = 3                            # number of binary covariates
py = 3                               # number of outcomes
beta = matrix(runif(px*py, 1, 10), nrow = px, ncol = py) # fixed effects
sigma_u = 0.2                        # site RE sd
sigma_e = 0.5                        # residual sd (per outcome)
rho = 0.3                            # exchangeable residual correlation across outcomes

dat <- generate_data_mv(seed = 123698, H, m_hosp, px, p_bin, py, beta, sigma_u, sigma_e, rho)
dat
```

```{r}
source("Multi-LMM.R")

Y <- as.matrix(dat[, paste0("Y", 1:3)])
X <- as.matrix(dat[, paste0("X", 1:6)])
id.site <- dat$site

fit <- peal_profile_exch_RI(Y = Y, X = X, id.site = id.site)
fit$beta %>% matrix(nrow = px, ncol = py, byrow = F)

sqrt(fit$sigma_u2)
sqrt(fit$sigma2)
fit$rho
```

