---
title: "Multi-Analysis"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, eval = T, cache = F, warning = T, message = T)
library(tidyverse)
library(dplyr)
library(tidyr)
library(lme4)
library(MASS)  
library(data.table)
library(Matrix)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(out.width = "100%", fig.align = 'center')
```


```{r}
source("DGP.R")
H = 5                                # number of sites
m_hosp = sample(10:50, H, replace=TRUE) # patients per site (vector length H)
px = 6                               # number of covariates
p_bin = 3                            # number of binary covariates
py = 3                               # number of outcomes
beta = matrix(runif(px*py, 1, 10), nrow = px, ncol = py) # fixed effects
sigma_u = 0.2                        # site RE sd
sigma_e = 0.5                        # residual sd (per outcome)
rho = 0.3                            # exchangeable residual correlation across outcomes

dat <- generate_data_mv(seed = 123, H, m_hosp, px, p_bin, py, beta, sigma_u, sigma_e, rho)
dat
```

```{r}
mdat <- dat %>%
  pivot_longer(cols = c(Y1, Y2, Y3),
               names_to = "outcome",
               values_to = "value")

lme1 <- lme(value ~ outcome - 1 + X1 + X2 + X3 + X4 + X5, random = ~outcome - 1 | site, data = mdat)
lme2 <- update(lme1, weights = varIdent(form = ~1 | outcome), correlation = corSymm(form = ~1 | 
    site/patient))
lme2
VarCorr(lme2)
```






```{r}
set.seed(102)
n_indiv <- 200
n_per_indiv <- 4
n_tot <- n_indiv * n_per_indiv
id <- gl(n_indiv, n_per_indiv)  ## generate identifier columns
av_wealth <- rlnorm(n_indiv, 0, 1)  ## avg wealth of individuals
ac_wealth <- av_wealth[id] + rlnorm(n_tot, 0, 1)  ## wealth in each year:
av_ratio <- rbeta(n_indiv, 10, 10)  ## 50/50, close to Gaussian
## car/holiday ratio by year (larger shape parameter/less variability)
ac_ratio <- rbeta(n_tot, 2 * av_ratio[id], 2 * (1 - av_ratio[id]))
y.car <- (ac_wealth * ac_ratio)^0.25
y.hol <- (ac_wealth * (1 - ac_ratio))^0.25
Spending <- data.frame(y.hol, y.car, id)
qplot(y.hol, y.car, data = Spending) + geom_smooth(method = "lm")
mSpending <- Spending %>%
  mutate(obs = row_number()) %>%
  pivot_longer(cols = c(y.hol, y.car),
               names_to = "trait",
               values_to = "value")


library(nlme)
lme1 <- lme(value ~ trait - 1, random = ~trait - 1 | id, data = mSpending)
lme2 <- update(lme1, weights = varIdent(form = ~1 | trait), correlation = corSymm(form = ~1 | 
    id/obs))
VarCorr(lme2)
```

